wx:
  login:
    client-id: wx59cfe0c2243b43c6
    client-secret: 9bb6206f434ec3be82cb4d1c7ea8fb23
    callback-url: http://wogua.helloworld.center:9000/api/wx/auth/callback
    success-redirect-url: http://localhost:8081/login